---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  # NOTE: 13.0.113 breaks 'packages' recipe, see https://github.com/copious-cookbooks/base/issues/15

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/6
  - name: centos/7
  - name: debian/wheezy64
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[cop_base::default]
    attributes:
        environment_vars:
            testing: true
        selinux:
            dev_packages:
              enabled: true
