---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.1.31
  # NOTE: 13.1.31 Last tested version

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/6
  - name: centos/7
  - name: debian/wheezy64
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[cop_base::default]
    attributes:
        environment_vars:
            testing: true
        selinux:
            dev_packages:
              enabled: true
